version: '2'
services:
  jupyter:
    image: tensorflow/tensorflow:1.9.0-gpu-py3
    ports:
      - "8888:8888"
    volumes:
      - "/tmp/tensorflow_logs"
      - "./notebooks:/root/notebooks"
    command: ["jupyter", "notebook", "--allow-root", "/root/notebooks"]
  tensorboard:
    image: tensorflow/tensorflow:1.9.0-gpu-py3
    ports:
      - "6006:6006"
    volumes_from:
      - jupyter
    command: ["tensorboard", "--logdir", "/tmp/tensorflow_logs", "--host", "0.0.0.0"]
